name: Deploy Portfolio

on:
  push: # Trigger on push
    branches:
      - master # Update to preferred branch
  workflow_dispatch:  # Enables manual triggering
  schedule:
    - cron: '*/30 * * * *'  # Scheduled every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MKDocs & Dependencies
        run: | 
          pip3 install mkdocs-material

      - name: Build MkDocs Site
        run: mkdocs build

      - name: Debugging Operations
        run: pwd && tree -L 1

      - name: Deploy Site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # personal_token: ${{ secrets.MKDOCS_DEPLOY_TOKEN }}
          publish_dir: site
