name: Deploy Portfolio

on:
  push: # Trigger on repo push
    branches:
      - master
      - temp # Update to preferred branch
  workflow_dispatch: # Enables manual triggering
  schedule:
    - cron: '0 0 * * *'  # Run Jobs daily by 12am

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MKDocs & Dependencies
        run: | 
          # https://squidfunk.github.io/mkdocs-material/customization/
          pip3 install -r requirements.txt

      - name: Build MkDocs Site
        run: mkdocs build

      - name: Debugging Operations
        run: pwd && tree -L 1

      - name: Deploy Site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # ssh-keygen -t rsa -b 4096 -C "$(whoami)@$(hostname)" -f ~/.ssh/id_rsa -N "" && cat ~/.ssh/id_rsa.pub
          # https://github.com/settings/keys
          # https://github.com/settings/personal-access-tokens
          # https://github.com/peaceiris/actions-gh-pages
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: site
